<a href="https://colab.research.google.com/github/Quanhongnguyentran/aaa/blob/main/Ba%CC%80i_t%C3%A2%CC%A3p_gi%C6%B0%CC%83a_ki%CC%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
from google.colab import drive
drive.mount('/content/drive')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression

Câu 1: Hãy tải về tập dữ liệu:
1. Breast cancer
2. Wine

In [ ]:
import pandas as pd
# reading csv files
datawine =  pd.read_csv('wine.data', sep=",")
X = datawine.iloc[:, :-1].values
y = datawine.iloc[:, -1].values
databreast =  pd.read_csv('breast-cancer-wisconsin.data', sep=",")
X = databreast.iloc[:, :-1].values
y = databreast.iloc[:, -1].values



In [ ]:
#Chuyển đổi các ô trống sang NaN
databreast.replace("?", np.nan, inplace=True) 
#Xóa các hàng có giá trị NaN
databreast.dropna(inplace=True) 
databreast.sample(10)

NameError: ignored

In [ ]:
datawine

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3    2.93   735  
4    2.85  1450  
..    ...   ...  
172  1.74   740  
173  1.56   750  
174  1.56   835  
175  1.62   840  
176  1.60   560  

[177 rows x 14 columns]

Những dữ liệu này là kết quả phân tích hóa học của các loại rượu vang được trồng ở cùng một vùng ở Ý nhưng có nguồn gốc từ ba giống cây trồng khác nhau. Phân tích đã xác định số lượng của 13 thành phần được tìm thấy trong mỗi loại trong số ba loại rượu vang.

Các thuộc tính là

1) Rượu

2) Axit malic

3) Tro

4) Độ kiềm của tro

5) Magiê

6) Tổng số phenol

7) Flavanoid

8) Phenol không flavanoid

9) Proanthocyanin

10) Cường độ màu

11)Hue

12)OD280/OD315 của rượu pha loãng

13)Proline

In [ ]:
databreast


1000025  5   1  1.1  1.2  2 1.3   3  1.4  1.5  2.1
0    1002945  5   4    4    5  7  10   3    2    1    2
1    1015425  3   1    1    1  2   2   3    1    1    2
2    1016277  6   8    8    1  3   4   3    7    1    2
3    1017023  4   1    1    3  2   1   3    1    1    2
4    1017122  8  10   10    8  7  10   9    7    1    4
..       ... ..  ..  ...  ... ..  ..  ..  ...  ...  ...
693   776715  3   1    1    1  3   2   1    1    1    2
694   841769  2   1    1    1  2   1   1    1    1    2
695   888820  5  10   10    3  7   3   8   10    2    4
696   897471  4   8    6    4  3   4  10    6    1    4
697   897471  4   8    8    5  4   5  10    4    1    4

[698 rows x 11 columns]

1.1 Tập dữ liệu Breast Cancer Wisconsin
Bộ dữ liệu BCW chứa 699 mẫu bệnh phẩm được lấy từ các tế bào ung thư vú của bệnh nhân
Có 11 thuộc tính cho mỗi quan sát tương ứng với miền giá trị của nó

1 Sample code number (ID - Các con số dùng để định danh)

2 Clump Thickness (1-10) (Tức là giá trị của nó là số nguyên nằm từ 1 đến 10)

3 Uniformity of Cell Size (1-10)

4 Uniformity of Cell Shape (1-10)

5 Marginal Adhesion (1-10)

6 Single Epithelial Cell Size (1-10)

7 Bare Nuclei (1-10)

8 Bland Chromatin (1-10)

9 Normal Nucleoli (1-10)

10 Mitoses (1-10)

11 Class (2- cho bệnh lành tính và 4 - cho bệnh ác tính) 

Câu 2: Đối với từng tập dữ liệu hãy xác định:
1. Thuộc tính nào đóng vai trò nhãn lớp?

  -Biến class đóng vai trò nhãn lớp
2. Tập dữ liệu nào phục vụ bài toán phân lớp nhị phân? Bài toán phân lớp đa nhãn?

  -Tập dữ liệu breast phục vụ cho bài toán nhị phân

  -Tập dữ liệu wine phục vụ cho bài toán phân lớp đa nhãm

3. Thuộc tính nào không cần thiết trong huấn luyện mô hình?

  -Thuộc tính id là không cần thiết trong huấn luyện mô hình


Câu 3: Hãy xây dựng mô hình phân lớp LogisticRegression, k-NN và Naïve Bayes cho 2 tập dữ
liệu trên. Yêu cầu:
1. Xác định nhãn lớp có cân bằng hay không?
2. Phân chia train – test theo tỉ lệ 80% - 20% có cần thực hiện xáo trộn dữ liệu hay không?
3. Thông báo kết quả 10-fold CV của quá trình huấn luyện từng mô hình (sử dụng
cross_val_scores)
4. Dựa vào kết quả dự đoán của từng mô hình - ŷ và tập dữ liệu kiểm chứng - ytest, hãy:

a. Đánh giá hiệu năng của từng mô hình theo các bộ chỉ số: (i) accuracy; (ii) precision; (iii) recall; và (iv) f1-measure.

b. Vẽ bảng ghi kết quả so sánh các chỉ số trên của từng mô hình

c. Xác định mô hình vượt trội?

In [1]:
# nhãn lớp cân bằng
from sklearn import datasets
import numpy as np
 
X = datawine.iloc[:, :-1].values
y = datawine.iloc[:, -1].values
 
X_imb = np.vstack((X[y == 1], X[y == 0][:30]))
y_imb = np.hstack((y[y == 1], y[y == 0][:30]))


NameError: ignored

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])

In [ ]:
X_train

array([[ 1.  , 13.3 ,  1.72, ...,  3.95,  1.02,  2.77],
       [ 2.  , 13.49,  1.66, ...,  3.74,  0.98,  2.78],
       [ 3.  , 13.48,  1.67, ..., 11.75,  0.57,  1.78],
       ...,
       [ 2.  , 12.42,  2.55, ...,  2.7 ,  0.86,  3.3 ],
       [ 2.  , 12.08,  1.39, ...,  2.9 ,  0.93,  3.19],
       [ 2.  , 11.84,  0.89, ...,  3.05,  0.79,  3.08]])

In [ ]:
y_train


array([1285,  472,  620,  564,  510,  660,  990,  365, 1295,  695, 1280,
        590, 1320,  680,  510,  885,  520,  500, 1015,  680,  278,  660,
        325,  495,  570,  630,  750,  415,  600,  886,  675, 1095, 1120,
        345,  845,  780,  560, 1515,  835,  685,  495,  420,  650,  680,
        530,  515,  714,  345,  760,  466, 1105,  406,  660, 1095,  970,
        434,  510,  495,  937,  465,  770, 1260,  625,  450,  392, 1280,
       1065, 1060, 1547,  985,  355,  640, 1130,  600,  520, 1285,  615,
        880, 1080,  915,  410,  312,  855, 1510,  718, 1290,  625, 1190,
       1235,  735,  415,  880, 1045,  607,  428,  630,  380,  630,  463,
       1450,  550,  438,  488,  480,  515,  678,  845,  740,  520, 1265,
        450, 1035,  580,  840, 1375,  650,  920,  380,  470, 1045, 1680,
        352,  795,  372,  290,  342,  520,  407,  750,  985, 1035,  562,
        502, 1020,  562,  750, 1150, 1285,  315,  385,  520])

In [ ]:
X_test

array([[  2.   ,  12.08 ,   1.83 ,   2.32 ,  18.5  ,  81.   ,   1.6  ,
          1.5  ,   0.52 ,   1.64 ,   2.4  ,   1.08 ,   2.27 ],
       [  2.   ,  12.07 ,   2.16 ,   2.17 ,  21.   ,  85.   ,   2.6  ,
          2.65 ,   0.37 ,   1.35 ,   2.76 ,   0.86 ,   3.28 ],
       [  3.   ,  13.17 ,   5.19 ,   2.32 ,  22.   ,  93.   ,   1.74 ,
          0.63 ,   0.61 ,   1.55 ,   7.9  ,   0.6  ,   1.48 ],
       [  2.   ,  11.81 ,   2.12 ,   2.74 ,  21.5  , 134.   ,   1.6  ,
          0.99 ,   0.14 ,   1.56 ,   2.5  ,   0.95 ,   2.26 ],
       [  2.   ,  11.46 ,   3.74 ,   1.82 ,  19.5  , 107.   ,   3.18 ,
          2.58 ,   0.24 ,   3.58 ,   2.9  ,   0.75 ,   2.81 ],
       [  3.   ,  13.23 ,   3.3  ,   2.28 ,  18.5  ,  98.   ,   1.8  ,
          0.83 ,   0.61 ,   1.87 ,  10.52 ,   0.56 ,   1.51 ],
       [  3.   ,  12.6  ,   2.46 ,   2.2  ,  18.5  ,  94.   ,   1.62 ,
          0.66 ,   0.63 ,   0.94 ,   7.1  ,   0.73 ,   1.58 ],
       [  2.   ,  13.67 ,   1.25 ,   1.92 ,  18.   ,  94.   , 

In [ ]:
y_test

array([ 480,  378,  725,  625,  562,  675,  695,  630,  830,  672, 1185,
        500,  830,  680,  780, 1035, 1480, 1060,  560,  425,  870, 1270,
        625, 1195,  550,  750,  680,  428,  450,  580,  480, 1050, 1310,
        720,  710, 1150])